[theme]
base = "light"
primaryColor = "#4338ca"
backgroundColor = "#faf7f2"
secondaryBackgroundColor = "#f4eee3"
textColor = "#000000"
font = "sans serif"

[client]
toolbarMode = "minimal"

[server]
headless = true
